#Site
title: Aria | Skrædderi, Rens & Vask
description: Aria skrædderi provide tailoring service with competitive prices and high service levels.
author: Afshin Moatari
baseurl: "/aria-website"
logo: "/assets/images/aria.svg"
favicon: "assets/images/favicon.png"

#Settings
uploads_dir: "assets/images"
_editable_regions:
  image:
    url_src: true
